//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int id { get; set; }
        [Display (Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Apellido")]
        public string apellido { get; set; }
        [Display(Name = "Fecha Nacimiento")]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage ="Debes Ingresar un mail correcto.")]
        public string email { get; set; }
        [Display(Name = "Usuario")]
        public string nombre_usuario { get; set; }
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string contraseña { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }

        public Usuario(int _id, string _nombre, string _apellido, Nullable<System.DateTime> _fecha_nacimiento, string _email, string _nombre_usuario, string _contraseña)
        {
            id = _id;
            nombre = _nombre;
            apellido = _apellido;
            fecha_nacimiento = _fecha_nacimiento;
            email = _email;
            nombre_usuario = _nombre_usuario;
            contraseña = _contraseña;
        }
    }
}
